export interface Color {
    BackgroundDark: string
    BackgroundDarkDrag: string
    BackgroundDarkFocus: string
    BackgroundDarkHover: string
    BackgroundDarkPress: string
    BackgroundLight: string
    BackgroundLightDrag: string
    BackgroundLightFocus: string
    BackgroundLightHover: string
    BackgroundLightPress: string
    Black: string
    Current: string
    ErrorContainerDark: string
    ErrorContainerDarkDrag: string
    ErrorContainerDarkFocus: string
    ErrorContainerDarkHover: string
    ErrorContainerDarkPress: string
    ErrorContainerLight: string
    ErrorContainerLightDrag: string
    ErrorContainerLightFocus: string
    ErrorContainerLightHover: string
    ErrorContainerLightPress: string
    ErrorDark: string
    ErrorDarkDrag: string
    ErrorDarkFocus: string
    ErrorDarkHover: string
    ErrorDarkPress: string
    ErrorLight: string
    ErrorLightDrag: string
    ErrorLightFocus: string
    ErrorLightHover: string
    ErrorLightPress: string
    GreenContainerDark: string
    GreenContainerDarkDrag: string
    GreenContainerDarkFocus: string
    GreenContainerDarkHover: string
    GreenContainerDarkPress: string
    GreenContainerLight: string
    GreenContainerLightDrag: string
    GreenContainerLightFocus: string
    GreenContainerLightHover: string
    GreenContainerLightPress: string
    GreenDark: string
    GreenDarkDrag: string
    GreenDarkFocus: string
    GreenDarkHover: string
    GreenDarkPress: string
    GreenLight: string
    GreenLightDrag: string
    GreenLightFocus: string
    GreenLightHover: string
    GreenLightPress: string
    InversePrimaryDark: string
    InversePrimaryLight: string
    InverseSurfaceDark: string
    InverseSurfaceDarkDrag: string
    InverseSurfaceDarkFocus: string
    InverseSurfaceDarkHover: string
    InverseSurfaceDarkPress: string
    InverseSurfaceLight: string
    InverseSurfaceLightDrag: string
    InverseSurfaceLightFocus: string
    InverseSurfaceLightHover: string
    InverseSurfaceLightPress: string
    OnBackgroundDark: string
    OnBackgroundLight: string
    OnErrorContainerDark: string
    OnErrorContainerLight: string
    OnErrorDark: string
    OnErrorLight: string
    OnGreenContainerDark: string
    OnGreenContainerLight: string
    OnGreenDark: string
    OnGreenLight: string
    OnInverseSurfaceDark: string
    OnInverseSurfaceLight: string
    OnPrimaryContainerDark: string
    OnPrimaryContainerLight: string
    OnPrimaryDark: string
    OnPrimaryLight: string
    OnRedContainerDark: string
    OnRedContainerLight: string
    OnRedDark: string
    OnRedLight: string
    OnSecondaryContainerDark: string
    OnSecondaryContainerLight: string
    OnSecondaryDark: string
    OnSecondaryLight: string
    OnSurfaceDark: string
    OnSurfaceLight: string
    OnTertiaryContainerDark: string
    OnTertiaryContainerLight: string
    OnTertiaryDark: string
    OnTertiaryLight: string
    OutlineDark: string
    OutlineLight: string
    PrimaryContainerDark: string
    PrimaryContainerDarkDrag: string
    PrimaryContainerDarkFocus: string
    PrimaryContainerDarkHover: string
    PrimaryContainerDarkPress: string
    PrimaryContainerLight: string
    PrimaryContainerLightDrag: string
    PrimaryContainerLightFocus: string
    PrimaryContainerLightHover: string
    PrimaryContainerLightPress: string
    PrimaryDark: string
    PrimaryDarkDrag: string
    PrimaryDarkFocus: string
    PrimaryDarkHover: string
    PrimaryDarkPress: string
    PrimaryLight: string
    PrimaryLightDrag: string
    PrimaryLightFocus: string
    PrimaryLightHover: string
    PrimaryLightPress: string
    RedContainerDark: string
    RedContainerDarkDrag: string
    RedContainerDarkFocus: string
    RedContainerDarkHover: string
    RedContainerDarkPress: string
    RedContainerLight: string
    RedContainerLightDrag: string
    RedContainerLightFocus: string
    RedContainerLightHover: string
    RedContainerLightPress: string
    RedDark: string
    RedDarkDrag: string
    RedDarkFocus: string
    RedDarkHover: string
    RedDarkPress: string
    RedLight: string
    RedLightDrag: string
    RedLightFocus: string
    RedLightHover: string
    RedLightPress: string
    SecondaryContainerDark: string
    SecondaryContainerDarkDrag: string
    SecondaryContainerDarkFocus: string
    SecondaryContainerDarkHover: string
    SecondaryContainerDarkPress: string
    SecondaryContainerLight: string
    SecondaryContainerLightDrag: string
    SecondaryContainerLightFocus: string
    SecondaryContainerLightHover: string
    SecondaryContainerLightPress: string
    SecondaryDark: string
    SecondaryDarkDrag: string
    SecondaryDarkFocus: string
    SecondaryDarkHover: string
    SecondaryDarkPress: string
    SecondaryLight: string
    SecondaryLightDrag: string
    SecondaryLightFocus: string
    SecondaryLightHover: string
    SecondaryLightPress: string
    SurfaceDark: string
    SurfaceDarkDrag: string
    SurfaceDarkFocus: string
    SurfaceDarkHover: string
    SurfaceDarkPress: string
    SurfaceLight: string
    SurfaceLightDrag: string
    SurfaceLightFocus: string
    SurfaceLightHover: string
    SurfaceLightPress: string
    TertiaryContainerDark: string
    TertiaryContainerDarkDrag: string
    TertiaryContainerDarkFocus: string
    TertiaryContainerDarkHover: string
    TertiaryContainerDarkPress: string
    TertiaryContainerLight: string
    TertiaryContainerLightDrag: string
    TertiaryContainerLightFocus: string
    TertiaryContainerLightHover: string
    TertiaryContainerLightPress: string
    TertiaryDark: string
    TertiaryDarkDrag: string
    TertiaryDarkFocus: string
    TertiaryDarkHover: string
    TertiaryDarkPress: string
    TertiaryLight: string
    TertiaryLightDrag: string
    TertiaryLightFocus: string
    TertiaryLightHover: string
    TertiaryLightPress: string
    Transparent: string
    White: string
}

export type Interval =
    | '1'
    | 'b2'
    | '2'
    | '#2'
    | 'b3'
    | '3'
    | '#3'
    | 'b4'
    | '4'
    | '#4'
    | 'b5'
    | '5'
    | '#5'
    | 'b6'
    | '6'
    | '#6'
    | 'b7'
    | '7'

export type Note =
    | 'C'
    | 'C#'
    | 'Db'
    | 'D'
    | 'D#'
    | 'Eb'
    | 'E'
    | 'F'
    | 'F#'
    | 'Gb'
    | 'G'
    | 'G#'
    | 'Ab'
    | 'A'
    | 'A#'
    | 'Bb'
    | 'B'

export type Scale = {
    name: string
    intervals: Interval[]
}
