import { Color } from '@types'
import tailwindConf from './tailwind.colors'

const tailwindColors = tailwindConf as Record<string, string>

export const colors: Color = {
    BackgroundDark: tailwindColors['background-dark'],
    BackgroundDarkDrag: tailwindColors['background-dark-drag'],
    BackgroundDarkFocus: tailwindColors['background-dark-focus'],
    BackgroundDarkHover: tailwindColors['background-dark-hover'],
    BackgroundDarkPress: tailwindColors['background-dark-press'],
    BackgroundLight: tailwindColors['background-light'],
    BackgroundLightDrag: tailwindColors['background-light-drag'],
    BackgroundLightFocus: tailwindColors['background-light-focus'],
    BackgroundLightHover: tailwindColors['background-light-hover'],
    BackgroundLightPress: tailwindColors['background-light-press'],
    Black: tailwindColors.black,
    Current: tailwindColors.current,
    ErrorContainerDark: tailwindColors['error-container-dark'],
    ErrorContainerDarkDrag: tailwindColors['error-container-dark-drag'],
    ErrorContainerDarkFocus: tailwindColors['error-container-dark-focus'],
    ErrorContainerDarkHover: tailwindColors['error-container-dark-hover'],
    ErrorContainerDarkPress: tailwindColors['error-container-dark-press'],
    ErrorContainerLight: tailwindColors['error-container-light'],
    ErrorContainerLightDrag: tailwindColors['error-container-light-drag'],
    ErrorContainerLightFocus: tailwindColors['error-container-light-focus'],
    ErrorContainerLightHover: tailwindColors['error-container-light-hover'],
    ErrorContainerLightPress: tailwindColors['error-container-light-press'],
    ErrorDark: tailwindColors['error-dark'],
    ErrorDarkDrag: tailwindColors['error-dark-drag'],
    ErrorDarkFocus: tailwindColors['error-dark-focus'],
    ErrorDarkHover: tailwindColors['error-dark-hover'],
    ErrorDarkPress: tailwindColors['error-dark-press'],
    ErrorLight: tailwindColors['error-light'],
    ErrorLightDrag: tailwindColors['error-light-drag'],
    ErrorLightFocus: tailwindColors['error-light-focus'],
    ErrorLightHover: tailwindColors['error-light-hover'],
    ErrorLightPress: tailwindColors['error-light-press'],
    GreenContainerDark: tailwindColors['green-container-dark'],
    GreenContainerDarkDrag: tailwindColors['green-container-dark-drag'],
    GreenContainerDarkFocus: tailwindColors['green-container-dark-focus'],
    GreenContainerDarkHover: tailwindColors['green-container-dark-hover'],
    GreenContainerDarkPress: tailwindColors['green-container-dark-press'],
    GreenContainerLight: tailwindColors['green-container-light'],
    GreenContainerLightDrag: tailwindColors['green-container-light-drag'],
    GreenContainerLightFocus: tailwindColors['green-container-light-focus'],
    GreenContainerLightHover: tailwindColors['green-container-light-hover'],
    GreenContainerLightPress: tailwindColors['green-container-light-press'],
    GreenDark: tailwindColors['green-dark'],
    GreenDarkDrag: tailwindColors['green-dark-drag'],
    GreenDarkFocus: tailwindColors['green-dark-focus'],
    GreenDarkHover: tailwindColors['green-dark-hover'],
    GreenDarkPress: tailwindColors['green-dark-press'],
    GreenLight: tailwindColors['green-light'],
    GreenLightDrag: tailwindColors['green-light-drag'],
    GreenLightFocus: tailwindColors['green-light-focus'],
    GreenLightHover: tailwindColors['green-light-hover'],
    GreenLightPress: tailwindColors['green-light-press'],
    InversePrimaryDark: tailwindColors['inverse-primary-dark'],
    InversePrimaryLight: tailwindColors['inverse-primary-light'],
    InverseSurfaceDark: tailwindColors['inverse-surface-dark'],
    InverseSurfaceDarkDrag: tailwindColors['inverse-surface-dark-drag'],
    InverseSurfaceDarkFocus: tailwindColors['inverse-surface-dark-focus'],
    InverseSurfaceDarkHover: tailwindColors['inverse-surface-dark-hover'],
    InverseSurfaceDarkPress: tailwindColors['inverse-surface-dark-press'],
    InverseSurfaceLight: tailwindColors['inverse-surface-light'],
    InverseSurfaceLightDrag: tailwindColors['inverse-surface-light-drag'],
    InverseSurfaceLightFocus: tailwindColors['inverse-surface-light-focus'],
    InverseSurfaceLightHover: tailwindColors['inverse-surface-light-hover'],
    InverseSurfaceLightPress: tailwindColors['inverse-surface-light-press'],
    OnBackgroundDark: tailwindColors['on-background-dark'],
    OnBackgroundLight: tailwindColors['on-background-light'],
    OnErrorContainerDark: tailwindColors['on-error-container-dark'],
    OnErrorContainerLight: tailwindColors['on-error-container-light'],
    OnErrorDark: tailwindColors['on-error-dark'],
    OnErrorLight: tailwindColors['on-error-light'],
    OnGreenContainerDark: tailwindColors['on-green-container-dark'],
    OnGreenContainerLight: tailwindColors['on-green-container-light'],
    OnGreenDark: tailwindColors['on-green-dark'],
    OnGreenLight: tailwindColors['on-green-light'],
    OnInverseSurfaceDark: tailwindColors['on-inverse-surface-dark'],
    OnInverseSurfaceLight: tailwindColors['on-inverse-surface-light'],
    OnPrimaryContainerDark: tailwindColors['on-primary-container-dark'],
    OnPrimaryContainerLight: tailwindColors['on-primary-container-light'],
    OnPrimaryDark: tailwindColors['on-primary-dark'],
    OnPrimaryLight: tailwindColors['on-primary-light'],
    OnRedContainerDark: tailwindColors['on-red-container-dark'],
    OnRedContainerLight: tailwindColors['on-red-container-light'],
    OnRedDark: tailwindColors['on-red-dark'],
    OnRedLight: tailwindColors['on-red-light'],
    OnSecondaryContainerDark: tailwindColors['on-secondary-container-dark'],
    OnSecondaryContainerLight: tailwindColors['on-secondary-container-light'],
    OnSecondaryDark: tailwindColors['on-secondary-dark'],
    OnSecondaryLight: tailwindColors['on-secondary-light'],
    OnSurfaceDark: tailwindColors['on-surface-dark'],
    OnSurfaceLight: tailwindColors['on-surface-light'],
    OnTertiaryContainerDark: tailwindColors['on-tertiary-container-dark'],
    OnTertiaryContainerLight: tailwindColors['on-tertiary-container-light'],
    OnTertiaryDark: tailwindColors['on-tertiary-dark'],
    OnTertiaryLight: tailwindColors['on-tertiary-light'],
    OutlineDark: tailwindColors['outline-dark'],
    OutlineLight: tailwindColors['outline-light'],
    PrimaryContainerDark: tailwindColors['primary-container-dark'],
    PrimaryContainerDarkDrag: tailwindColors['primary-container-dark-drag'],
    PrimaryContainerDarkFocus: tailwindColors['primary-container-dark-focus'],
    PrimaryContainerDarkHover: tailwindColors['primary-container-dark-hover'],
    PrimaryContainerDarkPress: tailwindColors['primary-container-dark-press'],
    PrimaryContainerLight: tailwindColors['primary-container-light'],
    PrimaryContainerLightDrag: tailwindColors['primary-container-light-drag'],
    PrimaryContainerLightFocus: tailwindColors['primary-container-light-focus'],
    PrimaryContainerLightHover: tailwindColors['primary-container-light-hover'],
    PrimaryContainerLightPress: tailwindColors['primary-container-light-press'],
    PrimaryDark: tailwindColors['primary-dark'],
    PrimaryDarkDrag: tailwindColors['primary-dark-drag'],
    PrimaryDarkFocus: tailwindColors['primary-dark-focus'],
    PrimaryDarkHover: tailwindColors['primary-dark-hover'],
    PrimaryDarkPress: tailwindColors['primary-dark-press'],
    PrimaryLight: tailwindColors['primary-light'],
    PrimaryLightDrag: tailwindColors['primary-light-drag'],
    PrimaryLightFocus: tailwindColors['primary-light-focus'],
    PrimaryLightHover: tailwindColors['primary-light-hover'],
    PrimaryLightPress: tailwindColors['primary-light-press'],
    RedContainerDark: tailwindColors['red-container-dark'],
    RedContainerDarkDrag: tailwindColors['red-container-dark-drag'],
    RedContainerDarkFocus: tailwindColors['red-container-dark-focus'],
    RedContainerDarkHover: tailwindColors['red-container-dark-hover'],
    RedContainerDarkPress: tailwindColors['red-container-dark-press'],
    RedContainerLight: tailwindColors['red-container-light'],
    RedContainerLightDrag: tailwindColors['red-container-light-drag'],
    RedContainerLightFocus: tailwindColors['red-container-light-focus'],
    RedContainerLightHover: tailwindColors['red-container-light-hover'],
    RedContainerLightPress: tailwindColors['red-container-light-press'],
    RedDark: tailwindColors['red-dark'],
    RedDarkDrag: tailwindColors['red-dark-drag'],
    RedDarkFocus: tailwindColors['red-dark-focus'],
    RedDarkHover: tailwindColors['red-dark-hover'],
    RedDarkPress: tailwindColors['red-dark-press'],
    RedLight: tailwindColors['red-light'],
    RedLightDrag: tailwindColors['red-light-drag'],
    RedLightFocus: tailwindColors['red-light-focus'],
    RedLightHover: tailwindColors['red-light-hover'],
    RedLightPress: tailwindColors['red-light-press'],
    SecondaryContainerDark: tailwindColors['secondary-container-dark'],
    SecondaryContainerDarkDrag: tailwindColors['secondary-container-dark-drag'],
    SecondaryContainerDarkFocus:
        tailwindColors['secondary-container-dark-focus'],
    SecondaryContainerDarkHover:
        tailwindColors['secondary-container-dark-hover'],
    SecondaryContainerDarkPress:
        tailwindColors['secondary-container-dark-press'],
    SecondaryContainerLight: tailwindColors['secondary-container-light'],
    SecondaryContainerLightDrag:
        tailwindColors['secondary-container-light-drag'],
    SecondaryContainerLightFocus:
        tailwindColors['secondary-container-light-focus'],
    SecondaryContainerLightHover:
        tailwindColors['secondary-container-light-hover'],
    SecondaryContainerLightPress:
        tailwindColors['secondary-container-light-press'],
    SecondaryDark: tailwindColors['secondary-dark'],
    SecondaryDarkDrag: tailwindColors['secondary-dark-drag'],
    SecondaryDarkFocus: tailwindColors['secondary-dark-focus'],
    SecondaryDarkHover: tailwindColors['secondary-dark-hover'],
    SecondaryDarkPress: tailwindColors['secondary-dark-press'],
    SecondaryLight: tailwindColors['secondary-light'],
    SecondaryLightDrag: tailwindColors['secondary-light-drag'],
    SecondaryLightFocus: tailwindColors['secondary-light-focus'],
    SecondaryLightHover: tailwindColors['secondary-light-hover'],
    SecondaryLightPress: tailwindColors['secondary-light-press'],
    SurfaceDark: tailwindColors['surface-dark'],
    SurfaceDarkDrag: tailwindColors['surface-dark-drag'],
    SurfaceDarkFocus: tailwindColors['surface-dark-focus'],
    SurfaceDarkHover: tailwindColors['surface-dark-hover'],
    SurfaceDarkPress: tailwindColors['surface-dark-press'],
    SurfaceLight: tailwindColors['surface-light'],
    SurfaceLightDrag: tailwindColors['surface-light-drag'],
    SurfaceLightFocus: tailwindColors['surface-light-focus'],
    SurfaceLightHover: tailwindColors['surface-light-hover'],
    SurfaceLightPress: tailwindColors['surface-light-press'],
    TertiaryContainerDark: tailwindColors['tertiary-container-dark'],
    TertiaryContainerDarkDrag: tailwindColors['tertiary-container-dark-drag'],
    TertiaryContainerDarkFocus: tailwindColors['tertiary-container-dark-focus'],
    TertiaryContainerDarkHover: tailwindColors['tertiary-container-dark-hover'],
    TertiaryContainerDarkPress: tailwindColors['tertiary-container-dark-press'],
    TertiaryContainerLight: tailwindColors['tertiary-container-light'],
    TertiaryContainerLightDrag: tailwindColors['tertiary-container-light-drag'],
    TertiaryContainerLightFocus:
        tailwindColors['tertiary-container-light-focus'],
    TertiaryContainerLightHover:
        tailwindColors['tertiary-container-light-hover'],
    TertiaryContainerLightPress:
        tailwindColors['tertiary-container-light-press'],
    TertiaryDark: tailwindColors['tertiary-dark'],
    TertiaryDarkDrag: tailwindColors['tertiary-dark-drag'],
    TertiaryDarkFocus: tailwindColors['tertiary-dark-focus'],
    TertiaryDarkHover: tailwindColors['tertiary-dark-hover'],
    TertiaryDarkPress: tailwindColors['tertiary-dark-press'],
    TertiaryLight: tailwindColors['tertiary-light'],
    TertiaryLightDrag: tailwindColors['tertiary-light-drag'],
    TertiaryLightFocus: tailwindColors['tertiary-light-focus'],
    TertiaryLightHover: tailwindColors['tertiary-light-hover'],
    TertiaryLightPress: tailwindColors['tertiary-light-press'],
    Transparent: tailwindColors.transparent,
    White: tailwindColors.white,
}
